package org.wallet.dap.common.dubbo;

public interface DubboServiceGroup {
    /** Dap */
    String DAP_SEQUENCE = "DAP_SEQUENCE";

    /** Gateway Client */
    String CLIENT_BIBOX = "CLIENT_BIBOX";
    String CLIENT_BINANCE = "CLIENT_BINANCE";
    String CLIENT_BITHUMB = "CLIENT_BITHUMB";
    String CLIENT_BIT_Z = "CLIENT_BIT_Z";
    String CLIENT_COIN_TIGER = "CLIENT_COIN_TIGER";
    String CLIENT_HPX = "CLIENT_HPX";
    String CLIENT_QUOTES = "CLIENT_QUOTES";
    String CLIENT_ZG_TOP = "CLIENT_ZG_TOP";

    String CLIENT_AWS_S3 = "CLIENT_AWS_S3";
    String CLIENT_BLOCK = "CLIENT_BLOCK";
    String CLIENT_DFUSE = "CLIENT_DFUSE";
    String CLIENT_EMAIL = "CLIENT_EMAIL";
    String CLIENT_OSS = "CLIENT_OSS";
    String CLIENT_SMS = "CLIENT_SMS";
    String CLIENT_JIGUANG = "CLIENT_JIGUANG";

    /** Service Admin */
    String SERVICE_SYS_DEPT = "SERVICE_SYS_DEPT";
    String SERVICE_SYS_DICT = "SERVICE_SYS_DICT";
    String SERVICE_SYS_LOG = "SERVICE_SYS_LOG";
    String SERVICE_SYS_MENU = "SERVICE_SYS_MENU";
    String SERVICE_SYS_ROLE = "SERVICE_SYS_ROLE";
    String SERVICE_SYS_USER = "SERVICE_SYS_USER";

    /** Service Application */
    String SERVICE_APP_ADVERT = "SERVICE_APP_ADVERT";
    String SERVICE_APP_CHAIN = "SERVICE_APP_CHAIN";
    String SERVICE_APP_CHAIN_NODE = "SERVICE_APP_CHAIN_NODE";
    String SERVICE_APP_INFO = "SERVICE_APP_INFO";
    String SERVICE_APP_INVITE_CODE = "SERVICE_APP_INVITE_CODE";
    String SERVICE_APP_LINK = "SERVICE_APP_LINK";
    String SERVICE_APP_MESSAGE = "SERVICE_APP_MESSAGE";
    String SERVICE_APP_TYPE = "SERVICE_APP_TYPE";
    String SERVICE_APP_TAG = "SERVICE_APP_TAG";
    String SERVICE_APP_VERSION = "SERVICE_APP_VERSION";
    String SERVICE_APP_VISIT_LOG = "SERVICE_APP_VISIT_LOG";
    String SERVICE_STATISTICS = "SERVICE_STATISTICS";

    /** Service Table Ext Attr */
    String SERVICE_TABLE_EXT_ATTR = "SERVICE_TABLE_EXT_ATTR";
    String SERVICE_TABLE_EXT_ATTR_VALUE = "SERVICE_TABLE_EXT_ATTR_VALUE";

    /** Service Wallet */
    String SERVICE_WALLET_COIN = "SERVICE_WALLET_COIN";
    String SERVICE_WALLET_COIN_CONFIG = "SERVICE_WALLET_COIN_CONFIG";
    String SERVICE_WALLET_COIN_ORDER = "SERVICE_WALLET_COIN_ORDER";
    String SERVICE_WALLET_EXCHANGE = "SERVICE_WALLET_EXCHANGE";
    String SERVICE_WALLET_INFO = "SERVICE_WALLET_INFO";
    String SERVICE_WALLET_PAY_CONFIG = "SERVICE_WALLET_PAY_CONFIG";
    String SERVICE_WALLET_TRANSFER_LOG = "SERVICE_WALLET_TRANSFER_LOG";
}
